server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qq?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 913812
    hikari:
      minimum-idle: 10
      maximum-pool-size: 40
      auto-commit: true